# Using node 16.17.1
#
name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.17.1
      - run: yarn install
      - env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          repos/${{ github.repository }}/contributors > app/data/contrib.json
      - run: yarn build
      - name: add date
        run: |
          echo TIME=`date '+%Y-%m-%d-%H:%M:%S %Z'` >> $GITHUB_ENV
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
          keep_history: true
          committer: Mandakara Sadewa <mdswa@zxce3.net>
          author: Mandakara Sadewa <mdswa@zxce3.net>
          commit_message: "Update `${{ env.TIME }}`"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

